# image_effects module schema

# Schema for module settings.

image_effects.settings:
  type: config_object
  label: 'Image Effects settings'
  mapping:
    color_selector:
      type: mapping
      label: 'Color selector plugin'
      mapping:
        plugin_id:
          type: string
          label: 'Selected plugin id'
        plugin_settings:
          type: sequence
          label: 'Plugin settings'
          sequence:
            type: image_effects.plugin.color_selector.[%key]
    image_selector:
      type: mapping
      label: 'Image selector plugin'
      mapping:
        plugin_id:
          type: string
          label: 'Selected plugin id'
        plugin_settings:
          type: sequence
          label: 'Plugins settings'
          sequence:
            type: image_effects.plugin.image_selector.[%key]
    font_selector:
      type: mapping
      label: 'Font selector plugin'
      mapping:
        plugin_id:
          type: string
          label: 'Selected plugin id'
        plugin_settings:
          type: sequence
          label: 'Plugins settings'
          sequence:
            type: image_effects.plugin.font_selector.[%key]

# Schema for image_effects plugins settings.

image_effects.plugin.color_selector.*:
  type: mapping
  label: 'Color selector plugin settings'

image_effects.plugin.color_selector.html_color:
  type: mapping
  label: 'HTML color element'

image_effects.plugin.color_selector.farbtastic:
  type: mapping
  label: 'Farbtastic color picker'

image_effects.plugin.image_selector.*:
  type: mapping
  label: 'Image selector plugin settings'

image_effects.plugin.image_selector.basic:
  type: mapping
  label: 'Basic'

image_effects.plugin.image_selector.dropdown:
  type: mapping
  label: 'Dropdown'
  mapping:
    path:
      type: string
      label: 'Path where image files can be found'

image_effects.plugin.font_selector.*:
  type: mapping
  label: 'Font selector plugin settings'

image_effects.plugin.font_selector.basic:
  type: mapping
  label: 'Basic'

image_effects.plugin.font_selector.dropdown:
  type: mapping
  label: 'Dropdown'
  mapping:
    path:
      type: string
      label: 'Path where font files can be found'

# Image effects settings

image.effect.image_effects_auto_orient:
  type: mapping
  label: 'Automatically correct orientation'
  mapping:
    scan_exif:
      type: boolean
      label: 'Scan EXIF data when calculating styled image dimensions'

image.effect.image_effects_color_shift:
  type: mapping
  label: 'Shift image colors'
  mapping:
    RGB:
      type: string
      label: 'RGB color shift'

# The strip metadata effect has no settings.
image.effect.image_effects_strip_metadata:
  type: sequence

image.effect.image_effects_watermark:
  type: mapping
  label: 'Watermark image effect'
  mapping:
    placement:
      type: string
      label: 'Position of the watermark'
    x_offset:
      type: integer
      label: 'x offset'
    y_offset:
      type: integer
      label: 'y offset'
    opacity:
      type: integer
      label: 'opacity'
    watermark_image:
      type: string
      label: 'watermark image path'
